using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;

namespace ListTypesWithCustomAttribute
{
    class ListTypesWithCustomAttribute
    {
        static void Main(string[] args)
        {
            Utils.Utils.ShowHelpAndAbortIfNeeded(args, 2, @"


ListTypesRelatedToCassandraTables pathToDll CustomAttributeFullName
TypeDescriptorsJson is generated by CassandraDBtoCSharp.
Example:
ListTypesRelatedToCassandraTables C:\temp\classes\bin\x64\Debug\netcoreapp2.0\win10-x64\publish\pse.dll Cassandra.Mapping.Attributes.TableAttribute


");

        var assembly = Assembly.LoadFrom(args[0]);
        var exportedTypes = assembly.GetExportedTypes();
        var exportedTypesWithSpecifiedCustomAttribute = exportedTypes
            .Where(t =>
                    t.CustomAttributes.Any(a => a.AttributeType.FullName == args[1]))
                    .ToList();
        exportedTypesWithSpecifiedCustomAttribute
            .ForEach(t => Console.WriteLine(t.FullName));
        }
    }
}
